<div class="confirm">
	<img class="center" src="/img/shopbag.png" />
	<h1>Condizioni Generali di Vendita</h1>
	<p class="text-center"> 
		<strong></strong>
	</p>
	<p>
		Il presente sito (di seguito il "Sito") www.food-republic.it è di proprietà di Food Republic S.r.l., con sede legale in Via Fratta, 2, 31020 San Zenone degli Ezzelini, ed iscrizione presso il Registro delle Imprese di Treviso, P. IVA 04496450265, ed è dedicato alla vendita di generi alimentari.
		Food Republic S.r.l. osserva la normativa in materia di contratti conclusi a distanza di cui agli art. 50 e seguenti del D.Lgs 206/2005.
		Ti invitiamo a leggere attentamente le condizioni sotto riportate, ed a stamparle e/o salvarle su alto supporto duraturo a tua scelta
		DEFINIZIONI
		Salvo quanto diversamente ed espressamente previsto in altre specifiche disposizioni, i termini di seguito elencati hanno nelle presenti Condizioni Generali di Vendita il significato che ad essi è attribuito nelle seguenti definizioni:
		Per "Giorno Lavorativo"  si intendono i giorni in cui i nostri uffici sono aperti per le normali attività (generalmente tutti i giorni dalle ore 9 alle ore 18 esclusi sabato, domenica, le festività ed in occasione di alcune circostanze eccezionali di cui vi daremo tempestiva notizia su questo sito).
		"Eventi di Forza Maggiore" includono le situazioni risultanti (direttamente o indirettamente) da eventuali scioperi, serrate, incendi, inondazioni, comprovata impossibilità di procurarsi prodotti, materiali o servizi, guasti, ritardi da parte dei fornitori o dei corrieri, leggi o regolamenti governativi o qualsiasi altra causa o evento che esuli dal nostro controllo. Quanto sopra è fornito solo a titolo esemplificativo. Esistono altri eventi che possono avere carattere di forza maggiore.
		Per "Produttore" si intende, a prescindere dalla forma giuridica adottata per l’esercizio della propria attività e dal carattere individuale o meno, un’azienda che vende esclusivamente prodotti di propria produzione. Nel caso di prodotti trasformati, l’azienda deve utilizzare il più possibile materie prime prodotte localmente e provenienti da piccoli produttori. Ogni “Produttore” appartiene ad una Food Community, che corrisponde, salvo indicazioni diverse, al territorio di una Provincia. I Produttori sono selezionati da Food Republic, sulla base di una loro richiesta o su iniziativa di Food Republic. Potranno creare un proprio profilo su Food Republic solo dopo aver ricevuto la conferma che la loro richiesta di accredito è stata accettata e dopo aver ricevuto “password” e “username”, di cui diventano responsabili. Ove garantire la massima trasparenza, i produttori si impegnano a fornire a Food Republic informazioni dettagliate sulle loro tecniche produttive e a permettere l’accesso all’azienda da parte di personale autorizzato da Food Republic, accompagnato da altri membri della Food Community.
		Per “Prodotto” si intendono esclusivamente alimenti che siano stati prodotti nel rispetto dei limiti imposti dalla Normativa Comunitaria vigente (in particolare si ricordano, in maniera non esclusiva, Reg CE 710 del 2009; Reg CE 834/07 e 889/08; Reg CE 1804 del 1999 e D.M. 18354/09). I prodotti devono essere certificati come prodotti biologici, secondo le normative vigenti. Se all'interno di una Food Community non fossero presenti prodotti certificati e/o chi li produce non fosse interessato ad aderire a Food Republic, sarà possibile ricorrere a produttori sostitutivi – pur non certificati – che dichiarino formalmente di utilizzare pratiche produttive in linea con i Regolamenti Comunitari sopra richiamati. Tali produttori si assumono la responsalità di quanto dicharano nel loro profilo, che dovrà indicare chiaramente la mancanza di una certificazione. La loro partecipazione a Food Republic è intesa come primo passo verso l’adesione ad un progetto di garanzia partecipata. Qualora i produttori non certificati dichiarassero informazioni che risultano non veritiere o fuorvianti, o qualora non intendessero partecipare al progetto di garanzia partecipata – quanto sarà disponibile – Food Republic srl si riservà il diritto di estrometterli dalla piattaforma. 
		Per “Cittadino” o “Co-Produttore” si intende un singolo individuo che abbia un profilo all’interno di Food Republic, che gli permetta di visionare i prodotti disponibili e di ultimare l’acquisto.  
		Per “Gruppo” si intende un insieme di Cittadini o Co-Produttori che aderiscono ad uno stesso Gruppo. Ogni Gruppo è coordinato da un “Group Leader” che determina le regole per il funzionamento del Gruppo, descrivento nell’apposito profilo on-line il contributo che ciascun membro dovrá provvedere per il buon funzionamento del gruppo stesso.
		Per “Spaccio” si intende un negozio autorizzato alla vendita di prodotti alimentari, presso il quale il Cittadino/Co-Produttore può ritirare i prodotti acquistati su www.food-republic.it . I Cittadini/Co-Produttori possono, dopo essersi affiliati ad uno Spaccio, acquistare i prodotti disponibili, accettando di pagare una maggiorazione sul prezzo compresa tra 0 e 10% del costo del prodotto. Tale maggiorazione viene determinata direttamente dallo Spaccio.
		Per “Rivenditore” si intendono Commercianti, Grossisti, o ogni altro soggetto commerciale che sia autorizzato da Food Republic a creare un profilo per l’acquisto di prodotti sul sito “Food-republic.it”. In questa categoria possono rientrare, a titolo esemplificativo: piccoli negozi di alimentari, ristoranti, alberghi, bar, mense, altri trasformatori, ecc.
		1) Condizioni generali
		Tutte le modalità di vendita, consegna e pagamento sono elencate in dettaglio nelle varie sezioni del Sito – ed in particolare nel profilo di ogni Gruppo e/o Spaccio – e sono da ritenersi parte integrante e sostanziale del presente contratto. Le condizioni applicabili ad ogni singolo ordine saranno quelle esposte sul Sito al momento dell'ordine stesso, in cooperazione con i Group Leaders e gli Spacci. Le eventuali nuove condizioni saranno efficaci dal momento della pubblicazione sul Sito e si applicheranno alle sole vendite concluse successivamente.
		2) Proposta di Acquisto
		Con l'invio dell'ordine on-line, il Cittadino/Co-Produttore trasmette – per conto di Food Republic S.r.l. – una proposta di acquisto del prodotto e/o dei prodotti inseriti nel carrello. Quando il Cittadino/Co-Produttore effettua un ordine on-line per i prodotti che ha inserito nel carrello, accetta di acquistarli al prezzo ed ai termini indicati nelle Condizioni Generali di Vendita, ovvero al prezzo indicato dal Produttore, maggiorato del costo del trasporto e degli altri costi (IVA, costo per l’utilizzo della piattaforma Food Republic, eventuale costo del rivenditore).
		3) Prodotti
		L’aspetto dei prodotti consegnati potrebbe non coincidere con l’immagine rappresentata sul Sito nel caso in cui il Produttore abbia modificato la confezione e quindi per motivi indipendenti dalla volontà di Food Republic.
		4) Prodotti a peso variabile
		I prodotti a peso variabile (ad es. frutta, verdura, carne, pesce, prodotti di gastronomia e formaggi) vengono proposti nel Sito in misure e pesi indicativi. Il peso effettivo si determina solamente al momento della preparazione del prodotto, e puo' variare fino al 10% in piu' o in meno rispetto a quanto indicativamente proposto nel Sito. 
		5) Prezzi
		Alla spesa del Cittadino/Co-produttore si applicherà esclusivamente il prezzo (per unità di misura Euro/Kg per i prodotti a peso variabile e per confezione per tutti gli altri prodotti) calcolato al momento dell'ordine, senza alcuna considerazione di aumenti o diminuzioni di prezzo, anche per promozioni, eventualmente intervenute successivamente o precedentemente conclusesi. Tutti i prezzi sono comprensivi di IVA. Le spese di trasporto sono incluse nel prezzo pubblicato sul Sito.
		6) Accettazione degli ordini
		Food Republic invierà al Cittadino/Co-Produttore una e-mail di accettazione e di conferma dell'ordine contenente il numero, la data e l'importo complessivo dell'ordine nonchè le modalità di consegna del prodotto. Un riassunto giornaliero degli ordini ricevuti per ogni Produttore, con il dettaglio di ogni prodotto, verrá inviato a cura di Food Republic S.r.l. al Produttore il quale è tenuto a verificare la disponibilitá dei prodotti acquistati ed ad aggiornare i dati del profilo. Se, per qualsiasi motivo, il Produttore non fosse in grado di accettare l'ordine del Cittadino/Co-Produttore, lo comunicherà immediatamente al  Food Republic tramite il sito stesso. Il Produttore farà tutto quanto possibile per procurare dei prodotti simili o analoghi, facendone pronta comunicazione al Cittadino/Co-Produttore e a Food Republic.
		Food Republic si riserva comunque il diritto di non accettare l'ordine, a sua discrezione, ed in particolare quando il pagamento online non viene perfezionato. In ogni caso, l'intera procedura d'ordine sarà stata completata regolarmente ed in modo corretto senza alcuna evidenziazione di messaggi di errore da parte del Sito. Food Republic non inserirà nella spesa prodotti non espressamente ordinati dal Cittadino/Co-produttore.
		7) Conferma dell’ordine
		Nella sua casella di posta elettronica il Cittadino/Co-produttore riceverà conferma dell'ordine effettuato con il riepilogo dei prodotti, dei relativi prezzi, e delle condizioni generali e particolari applicabili all'ordine stesso. Inoltre, il Cittadino/Co-produttore potrà visualizzare i dettagli degli ordini in corso e di quelli già chiusi attraverso il suo profilo all’interno del Sito.
		8) Annullamento e modifica dell’ordine
		Food Republic, a seguito di impreviste difficoltà logistiche ed organizzative, potrà annullare l'ordine dandone comunicazione via e-mail al Cittadino/Co-produttore o, previo accordo con lo stesso, modificare giorno e/o ora di consegna.
		9) Consegna
		Food Republic consegna solamente nel luogo indicato dal Group Leader o dal Gestore dello Spaccio, all’interno del loro profilo nel Sito. Per effettuare un ordine, il Cittadino/Co-produttore dovrà richiedere e ricevere assenso a far parte di un Gruppo o ad affiliarsi ad uno Spaccio.
		Le consegne avverranno entro nell’orario indicato nel profilo del Group Leader o dello Spaccio. Food Republic cosegna ad ogni Gruppo/Spaccio solo prodotti non suddivisi secondo l’ordine di ogni singolo Cittadino/Co-produttore. Il Group Leader e lo Spaccio si faranno carico – eventualmente anche con l’ausilio del Cittadino/Co-produttore, se richiesto nel profilo del Group Leader – della suddivisione della consegna in pacchi corrispondenti all’ordine di ogni Cittadino/Co-produttore. 
		Per qualsiasi anomalia riscontrata il consumatore potrà comunque contattare direttamente Food Republic ai riferimenti indicati nell’Area Contatti del sito. Food Republic non sarà responsabile per eventuali ritardi occorsi durante il trasporto.
		Parimenti Food Republic non potrà essere ritenuta responsabile per qualsiasi perdita, danno, errata o mancata consegna causati da eventi e/o cause di forza maggiore o caso fortuito, quali a titolo indicativo ma non esaustivo: calamità naturali, avverse condizioni atmosferiche (quali ad esempio intense nevicate), eventuali scioperi (dei propri o di altri dipendenti), incidenti a mezzi di trasporto, esplosioni, o ogni altra causa, simile o diversa.
		La responsabilità per danni alle persone derivanti dal consumo di prodotti acquistati sul Sito è a carico dei Produttori che hanno reso disponibili i loro prodotti nel Sito. Food Republic non potrà essere ritenuta responsabile in alcun modo di tali danni.
		10) Prodotti disponibili e limitazioni all’acquisto
		Food Republic non sarà in alcun modo responsabile per la temporanea o definitiva indisponibilità di uno o piu' prodotti. Nel caso di indisponibilità, anche temporanea, dei prodotti richiesti, Food Republic si impegna a stornare al Cittadino/Co-produttore il prezzo corrispondente. Nel sito sono evidenziati i casi in cui valgano limitazioni all'acquisto di singoli prodotti.
		11) Mancata Consegna
		Per la consegna è necessaria la presenza del Group Leader o del Responsabile dello Spaccio o di un suo incaricato all'indirizzo ed all'orario indicato nell'ordine. Se essi (o la persona incaricata) non sono presente si procederà ad un secondo tentativo di consegna e verrà aperta una pratica di giacenza in caso di omesso ritiro definito Food Republic non rimborserà il costo della consegna e quello dei prodotti; sarà inoltre facoltà di Food Republic escludere il Gruppo o Spaccio dal servizio.
		12) Pagamento
		L'acquisto può essere pagato dal Cittadino/Co-produttore esclusivamente usando la Piattaforma di Paypal disponibile sul Sito e/o le Carte per il pagamento elettronico disponibili sul Sito. 
		Concludendo un acquisto con questo tipo di pagamento verrà visualizzata una pagina del sito PayPal dove inserire l'indirizzo e-mail personale e password del proprio conto PayPal, oppure accedere alla procedura per la creazione di un nuovo account paypal. Dopo la registrazione è possibile procedere ai pagamenti via PayPal senza dover più reinserirne i dati, anche per i successivi acquisti. Scegliendo questa modalità di pagamento l'importo viene addebitato direttamente sul conto PayPal. PayPal tutela le informazioni dell'acquirente.
		Ad ogni transazione eseguita con questo metodo verrà inviata un'e-mail di conferma da PayPal. L'importo dell'ordine viene addebitato sul conto PayPal al momento dell'acquisizione dell'ordine. In caso di annullamento l'importo viene rimborsato sul conto PayPal del Cittadino/Co-produttore.
		Si accettano pagamenti esclusivamente da utenti registrati sul sito PayPal italiano.
		13) Diritto di Recesso
		I diritti del Cittadino/Co-produttore sono tutelati dal D.Lgs 206/2005. Inoltre, ai sensi dell'art. 5 del D. Lgs. n. 185/1999, il Cliente che per qualsiasi ragione non si ritenesse soddisfatto dell'acquisto effettuato, ha diritto di recedere dal contratto stipulato e di restituire i Prodotti ordinati eventualmente già consegnati, senza alcuna penalità e senza specificarne il motivo. Il Cittadino/Co-produttore ha, pertanto, il diritto di recedere dal contratto, anche parzialmente, senza spiegazioni e senza aggravio di spese, a condizione che il recesso sia comunicato mediante raccomandata A/R a Food Republic Srl Via Fratta 2, cap: 31020, San Zenone degli Ezzelini entro 10 giorni lavorativi dal giorno del ricevimento dei prodotti. La comunicazione può essere anticipata, entro lo stesso termine, tramite e-mail, fax o telegramma, a condizione che sia confermata mediante raccomandata A/R entro le 48 ore successive. Tale comunicazione dovrà specificare la volontà di recedere dall'acquisto ed il prodotto o i prodotti per i quali si intende esercitare il diritto di recesso, allegando copia della fattura/ricevuta.
		Qualora invece sia già avvenuta la consegna, il consumatore dovrà spedire al medesimo indirizzo sopra indicato a proprie spese i prodotti che intende rendere, sempre entro dieci giorni lavorativi decorrenti dalla data in cui ha ricevuto i prodotti, con la dicitura di “reso ordine” apposta sul pacco. Per verificare il rispetto del termine farà fede l’accettazione dell’ufficio postale o dello spedizioniere. Non verranno ritirati in nessun caso pacchi in contrassegno né in porto assegnato. Il Cittadino/Co-produttore dovrà quindi restituire a proprie spese il prodotto secondo le seguenti modalità: il prodotto acquistato dovrà essere integro e restituito nella confezione originale, completa in tutte le sue parti (comprese imballo ed eventuale documentazione e dotazione accessoria); per limitare danneggiamenti alla confezione originale, la scatola originale va inserita in una seconda scatola, evitando l’apposizione di etichette o nastri adesivi direttamente sulla confezione originale del prodotto; la spedizione, fino all’attestato di avvenuto ricevimento da parte di Food Republic, è sotto la completa responsabilità del cliente; Food Republic non risponde in nessun modo per danneggiamenti o furto/smarrimento di beni restituiti con spedizioni non assicurate.
		Se il recesso sarà stato esercitato conformemente alle modalità descritte, Food Republic provvederà a rimborsare la somma versata per l'acquisto del prodotto nel più breve tempo possibile e comunque entro 30 giorni dalla data in cui Food Republic è venuta a conoscenza dell'esercizio del diritto di recesso da parte del Cittadino/Co-produttore. Food Republic provvederà a rimborsare al cliente l’intero importo già pagato tramite procedura di storno dell’importo addebitato sulla Carta di Credito o a mezzo Bonifico Bancario. In quest’ultimo caso, sarà cura del cliente fornire tempestivamente le coordinate bancarie sulle quali ottenere il rimborso (Cod. IBAN dell’intestatario della fattura).  I Prodotti resi devono essere restituiti integri, non utilizzati e nella confezione originale.  Le uniche spese a carico del Cittadino/Co-Produttore per l'esercizio del diritto di recesso sono quelle dirette di restituzione dei Prodotti a Food Republic. Non vengono ritirati in nessun caso pacchi in contrassegno né in porto assegnato.
		Tuttavia nel caso in cui i prodotti non possiedano le caratteristiche essenziali promesse, presentino vizi essenziali, vi siano stati errori nella consegna degli stessi o comunque si tratti di causa imputabile a Food Republic Srl, verranno restituite anche le spese di spedizione per la consegna dei prodotti acquistati e l’eventuale diritto di contrassegno.
		Il diritto di recesso non è consentito nel caso di:
		a) acquisto di prodotti confezionati sigillati, aperti dal Cittadino/Co-produttore;
		b) di beni che per loro natura non possono essere rispediti o rischiano di deteriorarsi o alterarsi rapidamente (ad es. i prodotti alimentari freschi e deperibili come carne, pesce, surgelati, frutta, verdura, latticini, salumi e prodotti di gastronomia).
		14) Responsabilità
		Food Republic garantisce il rispetto della catena del freddo ed, in generale delle norme di qualità e alle certificazioni relative ai prodotti esclusivamente dal momento del ritiro nell’azienda del Produttore fino al momento della consegna presso il luogo indicato dal Gruppo o Spaccio; è esclusa ogni responsabilità relativa al cattivo stato dei prodotti dovuta ad impropria conservazione successiva al momento della consegna. Food Republic non è in alcun modo responsabile delle informazioni, dei dati e delle eventuali inesattezze tecniche o d'altra natura che potrebbero essere contenute nel Sito.
		Food Republic declina ogni responsabilità per danni diretti o indiretti di qualunque natura essi siano o sotto qualunque forma si manifestino, conseguenti all'utilizzo del Sito e/o delle notizie, foto ed informazioni ivi contenute e qualora la consegna avvenga, su richiesta del Group Leader o Spaccio, all'interno dell'abitazione o altro luogo indicato per la consegna. Food Republic non si assume alcuna responsabilità sulle informazioni fornite/acquisite dai singoli produttori o distributori.
		15) Privacy
		Food Republic procederà al trattamento dei dati personali del Cittadino/Co-produttore nel rispetto della normativa in materia di privacy come precisato in dettaglio nell'informativa nella sezione "Privacy" dell' "Aiuto" del Sito.
		16) Foro competente
		Ogni e qualsiasi controversia che dovesse insorgere in relazione all'applicazione, interpretazione ed esecuzione delle presenti condizioni generali di vendita, sarà inderogabilmente devoluta al giudice del luogo di residenza o di domicilio del consumatore, se ubicati nel territorio dello Stato.
	</p>
</div>